services:
    europeana.example.command :
        class: Europeana\Example\ExampleCommand
        arguments: ['@europeana.example.example']
    europeana.example.example :
        class: Europeana\Example\Example
        arguments: ['@europeana.search.request']
    europeana.search.request :
        class: Europeana\Search\Search
