services:
    europeana.example.command :
        class: Europeana\Example\ExampleCommand
        arguments: ['@europeana.example.example']
    europeana.example.example :
        class: Europeana\Example\Example
        arguments: ['@europeana.search.apiClient']
    europeana.search.apiclient :
        class: Europeana\Transport\ApiClient
    europeana.search.request :
        class: Europeana\Search\Search
