Colada\Europeana\Payload\SearchPayloadResponse:
    properties:
        action:
            type: string
        success:
            type: integer
        requestNumber:
            type: integer
        itemsCount:
            type: integer
        totalResults:
            type: integer
        items:
            type: ArrayCollection<Colada\Europeana\Model\Search\Item>
        facets:
            type: ArrayCollection<Colada\Europeana\Model\Search\Facet>
        breadCrumbs:
            type: ArrayCollection<Colada\Europeana\Model\Search\Breadcrumb>
        params:
            type: Colada\Europeana\Model\Search\Params
