Colada\Europeana\Payload\DatasetsPayloadResponse:
    properties:
        itemsCount:
            type: integer
        totalResults:
            type: integer
        items:
            type: ArrayCollection<Colada\Europeana\Model\Datasets\Item>