Colada\Europeana\Payload\ProviderPayloadResponse:
    properties:
        itemsCount:
            type: integer
        totalResults:
            type: integer
        items:
            type: ArrayCollection<Colada\Europeana\Model\Providers\Item>