Colada\Europeana\Payload\RecordPayloadResponse:
    properties:
        object:
            type: Colada\Europeana\Model\Record\Object
        similarItems:
            type: ArrayCollection<Colada\Europeana\Model\Record\SimilarItem>
