Colada\Europeana\Model\Search\Item:
    properties:
        #
        # Minimal Profile
        #
        dataProvider:
            type: ArrayCollection<string>
        dcCreator:
            type: ArrayCollection<string>
        edmIsShownAt:
            type: ArrayCollection<string>
        edmPlaceLatitude:
            type: ArrayCollection<string>
        edmPlaceLongitude:
            type: ArrayCollection<string>
        edmPreview:
            type: ArrayCollection<string>
        europeanaCompleteness:
            type: integer
        guid:
            type: string
        id:
            type: string
        link:
            type: string
        provider:
            type: ArrayCollection<string>
        rights:
            type: ArrayCollection<string>
        score:
            type: string
        title:
            type: ArrayCollection<string>
        type:
            type: string
        year:
            type: ArrayCollection<string>
        #
        # Standard Profile
        #
        # edmConceptTerm:
        #
        # edmConceptPrefLabel:
        #
        # edmConceptBroaderTerm:
        #
        # edmConceptBroaderLabel:
        #
        edmTimespanLabel:
            type: ArrayCollection<Colada\Europeana\Model\EDM\Label>
        # edmTimespanBegin:
        #
        # edmTimespanEnd:
        #
        # edmTimespanBroaderTerm:
        #
        # edmTimespanBroaderLabel:
        #
        # recordHashFirstSix:
        #
        ugc:
            type: ArrayCollection<boolean>
        completeness:
            type: integer
        # country:
        #
        europeanaCollectionName:
            type: ArrayCollection<string>
        # edmPlaceBroaderTerm:
        #
        # edmPlaceAltLabel:
        #
        # dctermsIsPartOf:
        #
        # timestampCreated:
        #
        # timestampUpdate:
        #
        language:
            type: ArrayCollection<string>
        #
        # Portal Profile
        #
        # dctermsSpatial:
        #
        edmPlace:
            type: ArrayCollection<string>
        #
        # edmTimespan:
        #
        edmAgent:
            type: ArrayCollection<string>
        edmAgentLabel:
            type: ArrayCollection<Colada\Europeana\Model\EDM\Label>
        dcContributor:
            type: ArrayCollection<string>
        #
        # Rich Portal
        #
        edmIsShownBy:
            type: ArrayCollection<string>
        dcDescription:
            type: ArrayCollection<string>
        edmLandingPage:
            type: ArrayCollection<string>
        #
        # Ungrouped
        #
        edmConceptLabel:
            type: ArrayCollection<Colada\Europeana\Model\EDM\Label>
        timestamp_created_epoch:
            type: integer
        timestamp_update_epoch:
            type: integer
        timestamp_created:
            type: string
        timestamp_update:
            type: string
        index:
            type: integer
        dcLanguage:
            type: ArrayCollection<string>
