Europeana\Model\Params:
    properties:
        query:
            type: string
        qf:
            type: string
        profiles:
            type: string
        start:
            type: integer
        rows:
            type: integer
