Europeana\Payload\SearchPayloadResponse:
    properties:
        action:
            type: string
        success:
            type: integer
        requestNumber:
            type: integer
        itemsCount:
            type: integer
        totalResults:
            type: integer
        items:
            type: ArrayCollection<Europeana\Model\Item>
